### ISSUE TITLE
Release dark mode for iOS

### ISSUE THREAD

**Issue by ThaTiemsz** [nullpixel1/todo#3]
### c**M**o**N** 
# j**U**s**T** d**O** i**T** 
u **L**i**L** c**N**t
### o**R** 
d**O**n**T** u **H**a**V**e t**H**e 

> # c**O**u**R**a**G**e

f**O**r i**T**

@nullpixel1

**Comment by nullpixel1** [comment]
Soon:tm: but wen I do it'll be

👌👀👌👀👌👀👌👀👌👀 good meme go౦ԁ mEme👌 thats ✔ some good👌👌meme right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good meme
